### ISSUE TITLE
Error: Out of executable memory at import 0

### ISSUE THREAD

**Issue by pannous** [swiftwasm/swiftwasm.org#1]
Dolphin Browser on iPad:

Error: Out of executable memory at import 0

**Comment by zhuowei** [comment]
@pannous Try a different browser: it doesn't happen in Chrome on iPad Air.

**Comment by MaxDesiatov** [comment]
As there haven't been any updates on this for almost a year, I'm closing this issue. Feel free to reopen it if the issue persists.
